# This workflow will build and push a new container image to Amazon ECR,
name: 'GitHub Actions to build and push docker image to ECR'

on: 
  workflow_dispatch:
    inputs:
       git-ref:
        description: Git Ref (Optional)
        required: false 
                   
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_UAT }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_UAT }}
        aws-region: us-east-1
    
    - name: Pull the Image from Github Package
      id: docker-pull
      run: |
        docker pull docker.pkg.github.com/rupesh2010/nodejs/nodejs:sha-bfa0b74
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Tag, and push image to UAT Amazon ECR
      id: build-image
      run: |
        set -x
        docker tag docker.pkg.github.com/rupesh2010/nodejs/nodejs:sha-bfa0b74 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_DEV_REGISTRY: ${{ secrets.registry }}
        ECR_REPOSITORY: nodejs
        IMAGE_TAG: ${{ steps.get_version.outputs.tag }} 
