name: Publish Docker image
on:
  push:
    branches: 
      - v1.0.0.0
    
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
     
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: Rupesh2010/nodejs/nodejs
          tag_with_sha: true
